/*

CREATE TABLE users(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id VARCHAR(10) UNIQUE NOT NULL,
	full_name VARCHAR NOT NULL,
	username VARCHAR UNIQUE,
	status VARCHAR
);

CREATE TABLE main_menus(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	menu_name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE internal_menus(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	menu_name VARCHAR UNIQUE NOT NULL,
	main_menu_name VARCHAR REFERENCES main_menus(menu_name) NOT NULL
);

CREATE TABLE last_menus(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	menu_name VARCHAR UNIQUE NOT NULL,
	internal_menu_name VARCHAR REFERENCES internal_menus(menu_name) NOT NULL
);

CREATE TABLE posts(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	post_path INT NOT NULL,
	last_menu_name VARCHAR REFERENCES last_menus(menu_name) NOT NULL
);

CREATE TABLE messages(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	send_type VARCHAR NOT NULL,
	sent INT NOT NULL,
	not_sent INT NOT NULL,
	message_path VARCHAR NOT NULL,
	start_time TIMESTAMP NOT NULL,
	end_time TIMESTAMP NOT NULL
);

CREATE TABLE admins(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	admin_id VARCHAR(10) NOT NULL,
	status VARCHAR DEFAULT 'sleep' NOT NULL
);

CREATE TABLE questions_suggestions(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id VARCHAR(10) REFERENCES users(user_id) NOT NULL,
	message_path TEXT NOT NULL
);

*/